#!/bin/sh

export SWARMIJI_HOME="/home/brian/src/clojush-swarm/swarmiji"
export SWARMIJI_ENV="development"
CLOJUSH_HOME="/home/brian/src/clojush-swarm/clojush"

echo "CLOJUSH_HOME is $CLOJUSH_HOME"
echo "SWARMIJI_HOME is ${SWARMIJI_HOME}"

cp=".:$CLOJUSH_HOME:${SWARMIJI_HOME}/src"

for f in ${SWARMIJI_HOME}/jars/*.jar
do 
    cp=$cp:$f
done

echo $cp

exec java -Xms256m -Xmx512m -cp ${cp} clojure.main $*
